name: release harmony

on:
  push:
    tags:
      - v*

jobs:
  check:
    name: Per-check for current tag
    runs-on: ubuntu-22.04
    continue-on-error: false
    outputs:
      tag_annotated: ${{ steps.check-tag-annotated.outputs.tag_annotated }}

    steps:
      - name: Checkout harmony core code
        uses: actions/checkout@v3
        with:
          path: harmony
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Check tag annotated
        id: check-tag-annotated
        run: |
          VERSION=$(git tag -l --sort=-v:refname | head -n 1)
          if git rev-parse $VERSION^{tag} -- &>/dev/null
          then
            echo "::set-output name=tag_annotated::true"
          else
            echo "::set-output name=tag_annotated::false"
          fi
        working-directory: harmony

  build:
    name: Build harmony binary
    needs: check
    runs-on: ${{ matrix.os }}
    if: needs.check.outputs.tag_annotated == 'true'
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Checkout dependence repo
        uses: actions/checkout@v3
        with:
          repository: harmony-one/mcl
          path: mcl

      - name: Checkout dependence repo
        uses: actions/checkout@v3
        with:
          repository: harmony-one/bls
          path: bls

      - name: Checkout harmony core code
        uses: actions/checkout@v3
        with:
          path: harmony
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up Go with go.mod
        uses: actions/setup-go@v3
        with:
          go-version-file: 'harmony/go.mod'

      - name: Get latest version and release
        run: |
          VERSION=$(git tag -l --sort=-v:refname | head -n 1 | tr -d v)
          RELEASE=$(git describe --long | cut -f2 -d-)
          echo "build_version=$VERSION" >> $GITHUB_ENV
          echo "build_release=$RELEASE" >> $GITHUB_ENV
        working-directory: harmony

      - name: Build harmony binary and packages for Linux
        if: matrix.os == 'ubuntu-22.04'
        run: |
          make linux_static
          mv ./bin/harmony ./bin/harmony-amd64
        working-directory: harmony

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: harmony
          path: harmony/bin/*
          retention-days: 1